### ISSUE TITLE
Izteicējs ar modificētāju apgrieztā vārdu secībā nepareizi UD

### ISSUE THREAD

**Issue by lrituma** [LUMII-AILab/CorporaTools#13]
sent_id = a-p3002_r6-p1s2 "sintezēt nespēj"
sent_id = a-p3298_r14-p1s2 "sakāpt nespēj"
sent_id = a-p387_r16-p1s7 "izdarīt nespētu"

**Comment by lauma** [comment]
Izskatās pēc kļūdas, bet pašlaik izteicēju pārveidošanas kods ir tik idiotiski sarežģīts, ka labāk ieviest sarunātās izmaiņas par vairāklīmeņu izteicējiem, izmest visu ar modalitāti saistīto koda mudžekli miskastē un uzrakstīt no jauna pāris rindiņās, jo vairāklīmeņu izteicējos tas būs vienkāršāk.

**Comment by lauma** [comment]
Pārtaisot xPred ar mod transformāciju (0ff97bfb66a3fafbd1200dc9ff6cd8a954c42233), šai problēmai vajadzētu būt atrisinātai.
