### ISSUE TITLE
Vai "būt" var būt VERB tags, ja to lieto cop lomā?

### ISSUE THREAD

**Issue by lauma** [LUMII-AILab/CorporaTools#14]
Spriežot pēc https://github.com/UniversalDependencies/docs/issues/497 diskusijas, mēs laikam vairs nedrīkstam tagot saitiņverbus būt kā VERB, nevis AUX.

**Comment by lrituma** [comment]
Jā, man ar tā pēc viņu shēmām sanāk, ka ir tikai kombinācijas postagam un lomai VERB + PRED, AUX + AUX, un AUX + COP

**Comment by lauma** [comment]
Pēc pēdējās palīgdarbības vārdu revolūcijas (ba72850db8807dcca80714ce52e79db32c72f90e) vajadzētu būt, ka tagad "būt", "kļūt", "tikt", "tapt", ja ir lietoti kā palīgdarbības vārdi, tad tiek tagoti kā AUX un nokļūst tikai lomās _aux_ un _cop_.

Ar pārējām saitiņām gan var gadīties visādi.
