### ISSUE TITLE
LVTB2UD dokumentācija

### ISSUE THREAD

**Issue by normundsg** [LUMII-AILab/CorporaTools#17]
Šo dokumentāciju - https://github.com/LUMII-AILab/Sembank#updating-from-treebankgit - vajadzētu pārvietot uz https://github.com/LUMII-AILab/CorporaTools/tree/master/LVTB2UD (vai citu atbilstošāku vietu).

Ja uzskati, ka 5. punkts galīgi neiederas zem CorporaTools, to var pārcelt uz https://github.com/LUMII-AILab/Sembank/tree/master/scripts#kamols-to-ud

**Comment by lauma** [comment]
Uz Treebank attiecināmā versijas sagatavošanas info glabājas https://gitlab.com/ailab/Treebank/-/blob/master/Docs/versijas.md tāpēc, ka tur bija ērti apkopot visus soļus kopā, nevis tikai UD transformāciju.
