### ISSUE TITLE
UD transformācija: #text lauka formatējuma gļuki

### ISSUE THREAD

**Issue by normundsg** [LUMII-AILab/CorporaTools#18]
Sk. https://github.com/LUMII-AILab/Treebank/issues/91

**Comment by lauma** [comment]
@normundsg Vai šis vēl jo projām ir spēkā?

**Comment by lauma** [comment]
@normundsg Vai šis vēl jo projām ir spēkā? Varētu būt, ka pēc tam, kad tika sakārtota tekstuālo labojumu atainošana, šis ir pazudis.

**Comment by lauma** [comment]
Labi, ja jauni piemēri nenāk, tad pašlaik taisu ciet. @normundsg , ja Tu ieraugi, ka šis tomēr atkal notiek, attaisi vēlreiz un ieliec piemēru.
