### ISSUE TITLE
Reziduālis "no" lomā

### ISSUE THREAD

**Issue by lrituma** [LUMII-AILab/CorporaTools#20]
Vajag paredzēt transformācijā, ka "no" lomu var aizpildīt arī reziduālis. Mums bija grūtības ar bučiņas apzīmējošām zvaigznītēm. Gan jau vēl kāds simbols var gadīties, kam jāieņem discours loma pie teikuma, tātad "no" loma mūsu kokubankā.

**Comment by lauma** [comment]
Ja runa ir par atkarību lomu, tad ar https://github.com/LUMII-AILab/CorporaTools/commit/61f946670e3f4bfd0c49bbb8efdf745d78ea03cc šis ir izdarīts.
