### ISSUE TITLE
Polarity aizpildīšana partikulām jā, nē, ne.

### ISSUE THREAD

**Issue by lrituma** [LUMII-AILab/CorporaTools#22]
Sakārtot kodā, ka tas attiecas uz lemmām _jā, , ne, nē_ ar tagu q, nevis qs, un neparedzēt, ka ir tādi izsauksmes vārdi. Pieņemu, ka arī jāpārbauda kods, ka izasuksmes vārdi arī ir tikai ar vienu taga pozīciju, jo nav saliktu izsauksmes vārdu vairs.
Paredzēt polarity aizpildīt _neg_ arī saiklim "ne".

**Comment by lauma** [comment]
Atrisināts.
