### ISSUE TITLE
UD->PML transformators ģenerē invalīdu failu.

### ISSUE THREAD

**Issue by lauma** [LUMII-AILab/CorporaTools#23]
Izmeklēt, kāpēc pielikumā esošajai rindkopai UD->PML transformators ir uztaisījis <xinfo> virsotni tieši zem <pmcinfo>.

[s166.zip](https://github.com/LUMII-AILab/CorporaTools/files/2048359/s166.zip)

**Comment by lauma** [comment]
Hei, @aznotins, vari iedot, kāds conllu fails bija rindkopai s166-p13?

**Comment by aznotins** [comment]
[s166-p13.conll.zip](https://github.com/LUMII-AILab/CorporaTools/files/2053449/s166-p13.conll.zip)

**Comment by lauma** [comment]
Vēl viens līdzīgs. 
[n378-p61.zip](https://github.com/LUMII-AILab/CorporaTools/files/2057497/n378-p61.zip)

**Comment by lauma** [comment]
Salabots ar https://github.com/LUMII-AILab/CorporaTools/commit/ac987c8f77a36593df8a96f646a37ee81be1f8a7
