### ISSUE TITLE
UD transformācijā ielikt "repeat" lomu

### ISSUE THREAD

**Issue by lrituma** [LUMII-AILab/CorporaTools#27]
Vienojāmies, ka kļūst par reperandum. Šobrīd shēmā iezīmēts, ka kļūst par dep. Korpusā dēļ reperandum izpratnes tiks zīmēts atkārtotais teikuma fragments par vecāku, bet pirmais, labotais vai atkārtotais - par bērnu.

**Comment by lauma** [comment]
Izdarīts ar https://github.com/LUMII-AILab/CorporaTools/commit/ae0969edc54a87c605b5ddfbbc04a13e617155f9
