### ISSUE TITLE
Defise kā vārda sastāvdaļa

### ISSUE THREAD

**Issue by lrituma** [LUMII-AILab/CorporaTools#29]
Lauma prasīja UD, viņi gribēja, lai marķē kā punct, bet mēs gribējām kā flat. Ir kaut kāds galalēmums? Tas jārealizē rīkā.

**Comment by lauma** [comment]
Runa ir par šo biļeti https://github.com/UniversalDependencies/docs/issues/608

**Comment by lauma** [comment]
Mans pirmais secinājums ir, ka teksta primitīvi ar tagu `z.*`, kas atrodas `unstruct` vai `namedEnt` ir UD jāmarķē kā punct. Pēc tam jāpaskatās, kas vēl apbēdina UD validatoru.

**Comment by lauma** [comment]
Liekas, ka tālāk tas vairs validatoru neapbēdina.
