### ISSUE TITLE
Jāpapildina transformācija par redukciju un "ne"

### ISSUE THREAD

**Issue by lrituma** [LUMII-AILab/CorporaTools#40]
Teikums, kurā palīgteikuma pred = "ne", ir saiklis un komats, nezin, ka augšā jāliek partikula:
a-p135-p6s3

**Comment by lauma** [comment]
Transformatoram pie verbālām redukcijām varētu uztaisīt otro soli, ka, ja nevar paņemt pēc UD likumiem, tad nevis ņemt pirmo, bet pamēģināt vispirms atrast pirmo nepieturzīmi un tikai tad ņemt vienkārši pirmo. Sk. EllipsisLogic.java 91-108

**Comment by lauma** [comment]
saistīts ar #31 un https://github.com/LUMII-AILab/Treebank/issues/119

**Comment by lauma** [comment]
a-p135-p6s3 šobrīd strādā, tur patiesībā bija palikusi palīgteikumu pārveidošanas kļūda.
