### ISSUE TITLE
Lai TREDā strādā morfoloģijas fīču noteicējs

### ISSUE THREAD

**Issue by lrituma** [LUMII-AILab/CorporaTools#6]
Pēc izmaiņām tagsetā jāizmaina arī treda lietas, lai korekti atpazīst tagu izmaiņas:
1) Nelokāmajiem lietvārdiem skaitlisun dzimte tiks likti 0
2) ģenitīveņiem dzimti un skaitli arī norādīs 0, deklinācija būs g
3) divdabjiem tiek pielikta salīdzināmās pakāpes pozīcija taga beigās - p, c, s vai 0.
4) prievārdiem tiek izņemta pēdējā pozīcija par vietas nozīmi,
5) saikļiem tiek noņemta pēdējā pozīcija par uzbūvi,
6) izsauksmes vārdiem tiek noņemta pēdējā pozīcija par vienkāršu vai saliktu, 
7) partikulām tiek noņemta pēdējā pozīcija par vienkāršu vai saliktu,
8) saīsinājumiem tiek ieviesta papildus pozīcija par veidu - n, p, v, a, r vai d.

**Comment by lauma** [comment]
Nulli jau drīkst likt visās pozīcijās, izņemot vārdšķiru.

**Comment by lauma** [comment]
Jaunajā TrEd moduļu repozitorijā  http://sintakse.korpuss.lv/rep/ ir lv-treebank 2.19, kur šim visam vajadzētu strādāt. Ja nestrādā, šo biļeti ar papildus komentāriem var atvērt atkal.
