### ISSUE TITLE
UD transformatoram pielikt goeswith

### ISSUE THREAD

**Issue by lauma** [LUMII-AILab/CorporaTools#9]
Vārdiem, kas M līmenī savienoti no diviem ar atstarpi atdalītiem vārdiem, UD jātaisa divi tokeni un jāliek loma goeswith.

**Comment by lauma** [comment]
Vispār jāpadomā, arī ko darīt, ja ir druķenei mainīga forma.

**Comment by normundsg** [comment]
Kādas tam ir konsekvences attiecībā uz paralēlo NE, FrameNet u.c. marķēšanu?
NE marķējam, balstoties uz tokenizāciju .m failos. FrameNet marķējam, balstoties uz CoNLL-U rezultātu.

**Comment by lauma** [comment]
Pēdējo mēnešu laikā šis ir ticis darīts, pārdarīts un izdarīts.
